spring:
  application:
    name: ddd-simple-board
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:test"
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
        show-sql: true
  flyway:
    enabled: false

server:
  port: 8080
